# Analysis options for Flutter project demonstrating GitHub Copilot best practices
# This configuration helps maintain code quality that Copilot can learn from

include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    # Helpful for Copilot to understand code patterns
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    always_specify_types: false  # Let Copilot infer when appropriate
    
    # Documentation rules that help Copilot
    public_member_api_docs: true
    comment_references: true
    
    # Consistency rules
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    
    # Import organization (helps Copilot learn patterns)
    directives_ordering: true
    sort_constructors_first: true
    sort_pub_dependencies: true
    
    # Code quality rules
    avoid_empty_else: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    
    # Widget specific rules for Flutter
    use_key_in_widget_constructors: true
    sized_box_for_whitespace: true