name: CI Golden Tests

on:
  pull_request:
    branches: [ main, master, develop ]
  push:
    branches: [ main, master, develop ]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  golden:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'

      - name: Fetch default branch safely
        run: |
          echo "Fetching default branch: ${{ github.event.repository.default_branch }}"
          git fetch --no-tags --prune --depth=1 origin \
            ${{ github.event.repository.default_branch }}:refs/remotes/origin/${{ github.event.repository.default_branch }}

      - name: Install dependencies
        run: flutter pub get

      - name: Run golden test
        run: flutter test --update-goldens test/golden/golden_notification_preview.dart

      - name: Check golden diff
        run: bash scripts/check_golden_diff.sh ${{ github.event.repository.default_branch }}

      - name: Upload golden artifact
        uses: actions/upload-artifact@v4
        with:
          name: notification_preview.png
          path: goldens/notification_preview.png

      - name: Post PR summary (optional)
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          if [ -f scripts/post-pr-summary.js ]; then
            node scripts/post-pr-summary.js
          else
            echo "PR summary script not found, skipping..."
          fi
