name: CI Golden Tests

on:
  pull_request:
    branches: [ main, master, develop ]
    paths:
      - "lib/**"
      - "test/golden/**"
      - "goldens/**"
      - "scripts/**"
      - ".github/workflows/ci-golden.yml"
      - "pubspec.yaml"
  push:
    branches: [ main, master, develop ]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  golden:
    name: Golden Tests and Artifacts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache pub
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.4'

      - name: Install dependencies
        run: flutter pub get

      - name: Run golden tests (produce goldens)
        env:
          GOLDEN_OUTDIR: build/goldens
        run: |
          mkdir -p "$GOLDEN_OUTDIR"
          # run tests; keep exit code so we can still collect artifacts
          flutter test --update-goldens --reporter=json > test-results.json || true
          # copy generated images (adjust paths if your tests put goldens elsewhere)
          cp -r test/golden/*.png "$GOLDEN_OUTDIR" 2>/dev/null || true
          cp -r goldens/* "$GOLDEN_OUTDIR" 2>/dev/null || true

      - name: Upload golden artifacts
        uses: actions/upload-artifact@v4
        with:
          name: golden-artifacts
          path: build/goldens

      - name: Compare goldens and set result
        id: compare
        run: |
          # simple diff detection: check for diff/ directories or any files named *.diff.png
          if [ -d build/goldens/diff ] && [ "$(ls -A build/goldens/diff | wc -l)" -gt 0 ]; then
            echo "diff_found=true" >> $GITHUB_OUTPUT
            echo "Found diffs in build/goldens/diff"
            exit 2
          fi
          if ls build/goldens/*.diff.png 1> /dev/null 2>&1; then
            echo "diff_found=true" >> $GITHUB_OUTPUT
            echo "Found diff pngs"
            exit 2
          fi
          echo "diff_found=false" >> $GITHUB_OUTPUT

      - name: Post PR comment with artifact link
        if: always()
        uses: actions/github-script@v6
        with:
          script: |
            const runUrl = `https://github.com/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID}`;
            const diffMessage = (process.env.DIFF === 'true') ? 'Golden diffs detected — review artifacts.' : 'No golden diffs detected.';
            const body = `Golden test run: ${runUrl}\n\n${diffMessage}\n\nDownload artifact named "golden-artifacts" from this workflow run to inspect images.`;
            await github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body
            });
        env:
          DIFF: ${{ steps.compare.outputs.diff_found }}

      - name: Fail when diffs exist
        if: steps.compare.outputs.diff_found == 'true'
        run: |
          echo "Golden diffs detected — failing job to block merge"
          exit 2
